# Generated by Django 6.0.7 on 2026-07-30 23:40

from datetime import time

from django.conf import settings
from django.db import migrations, models


def _convert_departure_times(apps, schema_editor):
    Schedule = apps.get_model("booking", "Schedule")
    for s in Schedule.objects.iterator():
        if isinstance(s.departure_time, str) and ":" in s.departure_time:
            h, m = s.departure_time.split(":")
            s.departure_time = time(int(h), int(m))
            s.save(update_fields=["departure_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_user_seathold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_convert_departure_times, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seathold',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='seathold',
            name='session_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seathold',
            name='travel_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['schedule', 'travel_date'], name='idx_booking_schedule_date'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['schedule', 'travel_date'], name='idx_seathold_schedule_date'),
        ),
    ]
